---
title: "fixations"
author: "Sam"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width=5, fig.height=3.75,fig.align = "center",cache=TRUE)
```

```{r, include=FALSE, echo=FALSE}

library(ggplot2)
library(reshape)
library(grid)
library(dplyr)
library(gridExtra)
library(lme4)
library(reghelper)
library(RColorBrewer)
library(robustbase)
library(latex2exp)
library(tidyr)
library(readr)
library(stringr)
library(viridis)


paper_theme <- theme_light() + theme( axis.title.x = element_text(size=18),
                                      axis.text.x=element_text(
                                        size = 16), 
                                      axis.title.y = element_text(size = 18, vjust = 1),
                                      axis.text.y  = element_text(size = 16),
                             strip.text=element_text(size=16),
                                      axis.line.x = element_line(colour = "black"), 
                                      axis.line.y = element_line(colour = "black"),
                                      legend.title=element_text(size=14),
                                      legend.text=element_text(size=12),
                                      panel.grid.major=element_blank(),
                                      panel.grid.minor=element_blank())  

binomial_smooth <- function(...) {
  geom_smooth(method = "glm", method.args = list(family = "binomial"), ...)
}


df <- read_csv('output/fixation_model_output.csv')


df_points <- df %>%
             filter(fixation_number == 0)

df_sub <- df %>%
          filter(current_fixation_idx == point_idx)

df_summary <- df_sub %>%
              group_by(id) %>%
              top_n(n=1, wt=fixation_number) %>%
              mutate(count=fixation_number+1) %>%
              mutate(err=(count - total_points)) %>%
              mutate(abs_err = abs(err)) %>%
              mutate(correct=1*(count==total_points))



```

```{r}


ggplot(data=df_summary, aes(x=n_true_clusters, y=abs_err)) +
      stat_summary(fun="mean", geom="point") +
      stat_summary(fun="mean", geom="line") +
      stat_summary(fun.data="mean_se", geom="errorbar", width=0.05) +
      #geom_jitter(width=0.2,height=0.05, alpha=0.1) +
        paper_theme

ggplot(data=df_summary, aes(x=total_points, y=abs_err)) +
      stat_summary(fun="mean", geom="point") +
      stat_summary(fun="mean", geom="line") +

        geom_jitter(width=0.2,height=0.05, alpha=0.1) +
        paper_theme



ggplot(data=df_summary, aes(x=total_points, y=abs_err, color=factor(n_true_clusters))) +
      stat_summary(fun="mean", geom="point") +
      stat_summary(fun="mean", geom="line") +
      stat_summary(fun.data="mean_se", geom="errorbar", width=0.05) +
#        geom_jitter(width=0.2,height=0.05, alpha=0.1) +
        paper_theme


ggplot(data=df_summary, aes(x=total_points, y=count)) +
        geom_abline(linetype="dotted")+
        geom_jitter(width=0.2,height=0.05, alpha=0.1) +

      stat_summary(fun="mean", geom="point") +
      stat_summary(fun="mean", geom="line") +
      stat_summary(fun.data="mean_se", geom="errorbar", width=0.05) +
        paper_theme




ggplot(data=df_summary, aes(x=total_points, y=err, color=factor(n_true_clusters), group=n_true_clusters)) +
        geom_jitter(width=0.2,height=0.05, alpha=0.1) +

      stat_summary(fun="mean", geom="point") +
      stat_summary(fun="mean", geom="line") +
      stat_summary(fun.data="mean_se", geom="errorbar", width=0.05) +
        paper_theme


ggplot(data=df_summary, aes(x=total_points, y=correct, color=factor(n_true_clusters), group=n_true_clusters)) +
        geom_jitter(width=0.2,height=0.05, alpha=0.1) +

      stat_summary(fun="mean", geom="point") +
      stat_summary(fun="mean", geom="line") +
      stat_summary(fun.data="mean_se", geom="errorbar", width=0.05) +
        paper_theme


```


```{r, fig.width=8, fig.height=3}


ggplot(data=df_points %>% filter(id < 36)) +
        geom_point(aes(x=x, y=y, color=factor(initial_cluster))) +
        geom_path(data=df_sub %>% filter(id < 36), aes(x=current_x, y=current_y)) +
        paper_theme +
        facet_wrap(~n_true_clusters~id, nrow=3) +
        paper_theme + theme(strip.text=element_blank(), axis.text.x=element_blank(), axis.text.y=element_blank()) +
        guides(color="none")



```



```{r}
func <- function(n, alpha) {
  return (1-(1/n)**alpha)
}

n <- seq.int(1,10)
alpha <- seq.int(0,0.4,by=0.1)

l_n <- length(n)
l_a <- length(alpha)
n <- rep(n, times=l_a)
alpha <- rep(alpha, each=l_n)



df <- data.frame(n, alpha) %>%
      rowwise() %>%
      mutate(p=func(n, alpha))

ggplot(data=df, aes(x=n, y=p, color=alpha, group=alpha)) +
      geom_line() +
      paper_theme +
      scale_color_gradientn(colors=c("blue","red","orange"))




```